Update build-kernel-op13r.yml

diff --git a/.github/workflows/build-kernel-op13r.yml b/.github/workflows/build-kernel-op13r.yml
--- a/.github/workflows/build-kernel-op13r.yml
+++ b/.github/workflows/build-kernel-op13r.yml
@@ -56,7 +56,7 @@ jobs:
       
       - name: Initialize and Sync Kernel Source
         run: |
-          echo "Creating folder for configuration: $CONFIG..."
+          echo "Creating folder for configuration: ${CONFIG}..."
           mkdir -p "$CONFIG"
           ls
           cd "$CONFIG"
@@ -76,10 +76,10 @@ jobs:
           
           echo "Adding KernelSU..."
           curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
-          #cd ./KernelSU-Next/kernel
-          #KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
-          #echo "KSU_VERSION=$KSU_VERSION"
-          #sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=12335/' ./Makefile
+          cd ./KernelSU-Next
+          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
+          echo "KSU_VERSION=$KSU_VERSION"
+          sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=${KSU_VERSION}/' ./kernel/Makefile
           
       - name: Apply SUSFS Patches
         run: |
@@ -155,8 +155,9 @@ jobs:
 
       - name: Run sed and perl Commands
         run: |
-          echo "Changing to configuration directory: $CONFIG..."
+          echo "Changing to configuration directory: ${CONFIG}..."
           cd "$CONFIG/kernel_platform"
+          ls
           
           echo "Running sed commands..."
           
@@ -164,7 +165,7 @@ jobs:
           sed -i 's/check_defconfig//' ./common/build.config.gki
           #sed -i '$s|echo "\$res"|echo "\$res-Wild+"|' ./common/scripts/setlocalversion
           sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
-          #sed -i 's/ -dirty//g' ./common/scripts/setlocalversion || echo "-dirty not found in common"
+          sed -i 's/ -dirty//g' ./common/scripts/setlocalversion || echo "-dirty not found in common"
           #sed -i 's/ -dirty//g' ./msm-kernel/scripts/setlocalversion || echo "-dirty not found in msm-kernel"
           sed -i 's|^source kernel_platform/oplus/build/oplus_setup.sh \$1 \$2|source kernel_platform/oplus/build/oplus_setup.sh \$1 \$2 \$3 \$4 \$5|' ./oplus/build/oplus_build_kernel.sh
          
@@ -172,7 +173,6 @@ jobs:
           cat ./common/scripts/setlocalversion
           echo "msm-kernel/scripts/setlocalversion"
           cat ./msm-kernel/scripts/setlocalversion
-          touch .scmversion
 
           # Run perl command to modify UTS_VERSION
           perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./common/scripts/mkcompile_h
@@ -183,7 +183,6 @@ jobs:
           cd "$CONFIG"
           
           echo "Building the kernel..."
-          touch .scmversion
           rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
           rm -rf ./kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
           rm -rf .git || echo "No .git found!"
