Update build-kernel-op13r.yml

diff --git a/.github/workflows/build-kernel-op13r.yml b/.github/workflows/build-kernel-op13r.yml
--- a/.github/workflows/build-kernel-op13r.yml
+++ b/.github/workflows/build-kernel-op13r.yml
@@ -4,7 +4,7 @@ on:
   workflow_call:  # This allows this workflow to be called from another workflow
   
 jobs:
-  build-kernel-a15-6-1-kernelsu-susfs:
+  build-kernel-a14-6-1-kernelsu-susfs:
     runs-on: ubuntu-latest
 
     steps:
@@ -63,7 +63,7 @@ jobs:
           
           # Initialize and sync kernel source
           echo "Initializing and syncing kernel source..."
-          $REPO init -u https://github.com/edjocute/kernel_manifest.git -b oneplus/sm8650 -m oneplus13r_v.xml --repo-rev=v2.16
+          $REPO init -u https://github.com/edjocute/kernel_manifest.git -b oneplus/sm8650 -m oneplus13r_v.xml --repo-rev=v2.16 --depth=1
           
           # Sync repo and apply patches
           $REPO --version
@@ -76,10 +76,10 @@ jobs:
           
           echo "Adding KernelSU..."
           curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
-          cd ./KernelSU-Next/kernel
+          #cd ./KernelSU-Next/kernel
           #KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
           #echo "KSU_VERSION=$KSU_VERSION"
-          sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=12335/' ./Makefile
+          #sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=12335/' ./Makefile
           
       - name: Apply SUSFS Patches
         run: |
@@ -164,9 +164,10 @@ jobs:
           sed -i 's/check_defconfig//' ./common/build.config.gki
           #sed -i '$s|echo "\$res"|echo "\$res-Wild+"|' ./common/scripts/setlocalversion
           sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
-          sed -i 's/ -dirty//g' ./common/scripts/setlocalversion || echo "-dirty not found in common"
-          sed -i 's/ -dirty//g' ./msm-kernel/scripts/setlocalversion || echo "-dirty not found in msm-kernel"
-          
+          #sed -i 's/ -dirty//g' ./common/scripts/setlocalversion || echo "-dirty not found in common"
+          #sed -i 's/ -dirty//g' ./msm-kernel/scripts/setlocalversion || echo "-dirty not found in msm-kernel"
+          sed -i 's|^source kernel_platform/oplus/build/oplus_setup.sh \$1 \$2|source kernel_platform/oplus/build/oplus_setup.sh \$1 \$2 \$3 \$4 \$5|' ./oplus/build/oplus_build_kernel.sh
+         
           echo "common/scripts/setlocalversion"
           cat ./common/scripts/setlocalversion
           echo "msm-kernel/scripts/setlocalversion"
@@ -191,7 +192,7 @@ jobs:
           #git add *
           #git commit -s -a -m "getting rid of -dirty"
           
-          ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki
+          ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki thin all none
 
       - name: Create Bootimgs Folder and Copy Images
         run: |
